repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=700"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: ^helm/templates/
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]

  - repo: https://github.com/crate-ci/typos
    rev: v1.14.9
    hooks:
      - id: typos
        args: []
        types_or:
          - javascript
          - python
