name: CI

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=actions/python-versions versioning=loose
  PYTHON_VERSION: 3.11.6

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Lint
        uses: nikaro/actions/pre-commit@5e7f51a4d9299d91ba67e1ca9004db211af62561 # 1.0.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
